# Generated by Django 2.1.5 on 2019-01-31 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('catalogid', models.AutoField(db_column='catalogid', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=20, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('color', models.CharField(blank=True, db_column='color', max_length=20, null=True)),
                ('tastingnotes', models.TextField(blank=True, db_column='tastingnotes', null=True)),
            ],
            options={
                'db_table': 'Catalog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catid', models.AutoField(db_column='catid', primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, db_column='type', max_length=20, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('invid', models.AutoField(db_column='invid', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='quantity', max_length=45, null=True)),
                ('acquiredate', models.DateTimeField(blank=True, db_column='acquiredate', null=True)),
                ('catalogid', models.ForeignKey(blank=True, db_column='catalogid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.Catalog')),
            ],
            options={
                'db_table': 'Inventory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('producerid', models.AutoField(db_column='producerid', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=45, null=True)),
                ('state', models.CharField(blank=True, db_column='state', max_length=2, null=True)),
                ('country', models.CharField(blank=True, db_column='country', max_length=2, null=True)),
            ],
            options={
                'db_table': 'Producer',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='categoryid',
            field=models.ForeignKey(blank=True, db_column='categoryid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.Category'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='producerid',
            field=models.ForeignKey(blank=True, db_column='producerid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.Producer'),
        ),
    ]
