# Generated by Django 2.1.5 on 2019-02-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20190131_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, db_column='type', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='country',
            field=models.CharField(blank=True, db_column='country', max_length=40, null=True),
        ),
    ]
