# Generated by Django 2.1.5 on 2019-02-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190201_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='variety',
            field=models.CharField(blank=True, db_column='variety', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=30, null=True),
        ),
    ]
