# Generated by Django 2.1.5 on 2019-02-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20190202_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=40, null=True),
        ),
    ]
