# Generated by Django 2.1.5 on 2019-02-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_uploadimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimages',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
