# Generated by Django 2.1.5 on 2019-02-11 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20190209_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'managed': True, 'ordering': ['name']},
        ),
    ]
