# Generated by Django 2.1.5 on 2019-02-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20190210_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'ordering': ['name', 'variety']},
        ),
    ]
