# Generated by Django 2.1.5 on 2019-02-12 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20190211_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='categoryid',
            field=models.ForeignKey(blank=True, db_column='categoryid', null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.Category'),
        ),
    ]
