# Generated by Django 2.1.5 on 2019-02-12 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20190212_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='producerid',
            field=models.ForeignKey(blank=True, db_column='producerid', null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.Producer'),
        ),
    ]
