# Generated by Django 2.1.5 on 2019-02-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20190212_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='catalogid',
            field=models.ForeignKey(blank=True, db_column='catalogid', null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.Catalog'),
        ),
    ]
