# Generated by Django 2.1.5 on 2019-02-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20190212_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=100, null=True),
        ),
    ]
