# Generated by Django 2.1.5 on 2019-02-13 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_auto_20190212_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredientid', models.AutoField(db_column='ingredientid', primary_key=True, serialize=False)),
                ('catalogid', models.ForeignKey(blank=True, db_column='catalogid', null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.Catalog')),
            ],
            options={
                'db_table': 'Inventory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipeid', models.AutoField(db_column='recipeid', primary_key=True, serialize=False)),
                ('name', models.IntegerField(blank=True, db_column='name', null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
            ],
            options={
                'db_table': 'Recipe',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipeid',
            field=models.ForeignKey(db_column='recipeid', null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.Recipe'),
        ),
    ]
