# Generated by Django 2.1.5 on 2019-02-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_auto_20190213_1204'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredient',
            table='Ingredient',
        ),
    ]
