# Generated by Django 2.1.5 on 2019-02-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_auto_20190213_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='catalogid',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipeid',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
