# Generated by Django 2.1.5 on 2019-02-13 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_auto_20190213_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredientid', models.AutoField(db_column='ingredientid', primary_key=True, serialize=False)),
                ('catalogid', models.ForeignKey(blank=True, db_column='catalogid', null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.Catalog')),
                ('recipeid', models.ForeignKey(db_column='recipeid', null=True, on_delete=django.db.models.deletion.PROTECT, to='tracker.Recipe')),
            ],
            options={
                'db_table': 'Ingredient',
                'managed': True,
            },
        ),
    ]
