# Generated by Django 2.1.5 on 2019-02-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='catalogid',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipeid',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
