# Generated by Django 2.1.5 on 2019-02-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_auto_20190213_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=100, null=True),
        ),
    ]
